title: digital.gov
email: DigitalGov@gsa.gov

twitter_username: digitalgov
# github_username:  18F

gems:

whitelist:

styles:
  # - /assets/uswds/css/uswds.min.css
  - /assets/main.css

# Exlude files from being present in the build site
exclude:
  - ".gitignore"
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - package.json
  - gulpfile.js
  - node_modules
  - README.md
  # - content/about/
  # - content/services/
  - content/communities/_x/
  # - content/resources/
  - content/resources/1/
  - content/resources/2/
  - content/resources/3/
  - content/pages/1/
  - content/pages/2/
  - content/pages/3/
  - content/pages/_x/
  - content/un-sorted/
  - content/pages/_x/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      permalink: news/:year/:month/:day/:title/
